# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33f630ccce11dde3b05e98a0999bb90676339a3053c24d61c189834575a2a272312152e8fc3c99187f39ac07fbf61e77999d42f5fbcf327e614a8a862dbefd78

test:
  secret_key_base: 37b2404e25b55f8d243187fb1cb94a588bd96057aa0f62721e1d5e48fe55c4650475b89d50628942751d8800177f3fb7a8a495c3ad8fc64ed37d59a25826849d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
